### ISSUE TITLE
cerbot issue: There is an existing account; registration of a duplicate account with this command is currently unsupported.

### ISSUE THREAD

**Issue by novafiddler** [adferrand/dnsrobocert#106]
Hello, I get the following issue:

`There is an existing account; registration of a duplicate account with this command is currently unsupported.`

This issue occurs randomly when creating a new machine and I've been dealing with it since the forced move from letsencrypt-dns (which just worked) to certbot-dns (which works less than half the time).

Here is what I use to spin up a docker container (on CentOS 8 along with a simple one line domains.conf):

```
docker run -d \
    --name letsencrypt-dns \
    --restart always \
    --volume /opt/docker/letsencrypt:/etc/letsencrypt \
    --env 'LETSENCRYPT_USER_MAIL=r******6@gmail.com' \
    --env 'LEXICON_PROVIDER=cloudflare' \
    --env 'LEXICON_CLOUDFLARE_USERNAME=r******6@gmail.com' \
    --env 'LEXICON_CLOUDFLARE_TOKEN=e*********f' \
    --dns 1.0.0.1 \
    --dns 1.1.1.1 \
    adferrand/letsencrypt-dns
```

The commands above no longer work, as I'm sure you already know.

Now, I use the following commands:

```
cat <<EOF | tee /opt/docker/dnsrobocert/config.yml
draft: false
acme:
  email_account: r*****6@gmail.com
  directory_url: https://acme-v02.api.letsencrypt.org/directory
  crontab_renew: 12 01,13 * * *
profiles:
- name: cf_profile
  provider: cloudflare
  provider_options:
    auth_username: r*****6@gmail.com
    auth_token: e*****f
certificates:
- domains:
  - sub.foundry.cx
  profile: cf_profile
EOF

docker rm -f certbot-dns
docker run -d \
  --name certbot-dns \
  -h certbot.foundry.cx \
  --env 'LEXICON_PROVIDER=cloudflare' \
  --restart always \
  -v /opt/docker/dnsrobocert:/etc/dnsrobocert \
  -v /opt/docker/letsencrypt:/etc/letsencrypt \
  --net=host \
adferrand/dnsrobocert
```

And its scuessful about 45% of the time. When it errors out it complains about multiple accounts. It does not matter what email I put, it complains. I've removed all formatting from the config.yml. 

Please advise and thank you for your time.

**Comment by adferrand** [comment]
Hello @novafiddler, sorry that it does not work great for you. Let's dig a little to find out what is going wrong.

So, I think the error about the duplicate account is misleading. It is because at each modification dnsrobocert (like letsencrypt-dns) before, will try to create an account, to be sure that it exists before issuing certificates: either there is no account and it will create it, or there is one and you see this error. But it is not a problem an its own, it is expected and certificates starts to be issued with the existing account.

I should certainly hide this output since it is certainly quite disturbing to troubleshoot.

So I think the real issue is somewhere else. Could you post the redacted logs you see when it is failing?

Concerning the YAML configuration itself, you can already remove some things that are correctly defaulted: namely, `acme.directory_url` and `acme.crontab_renew` are not necessary. First because the default URL is already the right one (and you can trigger staging tests with `acme.staging: true`, and second because I did not reimplement the cron customization yet (but it runs already randomly twice a day).

On the docker command, `LEXICON_PROVIDER` is not necessary. I expect you do not need the `--net=host` either. I see also that in the previous call, you specify the Cloudflare DNS for the docker. Do you have a specific reason for that? I do not see a direct implication in the failure, since you did not used the options to check DNS TXT entries propagation before certificate issuance, but it arouses my curiosity.

Note that I plan soon to add back configuration through environment variable, but in a way more structured manner.

**Comment by novafiddler** [comment]
First of all, without the LEXICON_PROVIDER variable defined, your docker container complains about not having a LEXICON provider.

As for this issue, I must move on because I do not have the time to troubleshoot all of these issues. the Linuxserver/letsencrypt package works as I'd expect and does the job.

Thank you anyway.

**Comment by adferrand** [comment]
Honestly if your purpose is to secure a single HTTP server, yes, there are better integrated tools to get what you need. DNSroboCert is more for situations where you want certificates out of these kind of HTTP services.

The fact that it is failing on `LEXICON_PROVIDER` environment variable indicates me that DNSroboCert goes in the legacy mode, trying to parse the file at `/etc/letsencrypt/domains.conf` and convert it into the new YAML configuration file. I am pretty sure that if you delete `domains.conf`, the container will behave consistently (in success or in failure), and my other comments on my previous post will apply.

There are still things that I do not understand here, like that normally, if `/etc/dnsrobocert/config.yml` exits, the entire legacy migration process should be skipped.

So anyway if you have time to post the log, I will be glad to analyze it. I know that migrations are fragile, and may not work as expected in specific situations. This is something I want to take care of, and hopefully avoid painful situations that you seems to encounter in the future.

**Comment by novafiddler** [comment]
No problem. I'll have to recreate the issue on a new machine because the
issue because this is a production machine, now.

I no longer maintain a domains.conf file on any letsencrypt instance fyi.
The commands above were ran on a clean system with no sign of your legacy
letsencrypt docker package. Every host (25-30) use your current package
around the globe.
