### ISSUE TITLE
outdated documentation regarding hetzner

### ISSUE THREAD

**Issue by pvdh** [adferrand/dnsrobocert#108]
Current documenation for provider "hetzner" says: "Specify type of hetzner account: by default hetzner robot (robot) or hetzner konsoleh (konsoleh)"
This might have been correct in the past (before 3.0.0?) and it might be correct for Lexicon provider hetzner_legacy, but it is simply not true for the current hetzner-provider which dropped support for konsoleh.

Source lexicon/providers/hetzner.py says:
It neither works for their web hosting offer "konsoleH" nor for the discontinued "Domain Robot" which are supported by the ``lexicon.providers.hetzner_legacy`` module.

Pity, really, since konsoleH is not outdated...

**Comment by adferrand** [comment]
The documentation is now updated with 3.3.1.

About why the old Hetzner provider, it is more a question for the Lexicon library, that DNSroboCert uses, but since I am also involved in Lexicon Iwill respond here.

We dropped it because it was already broken at this time, and because it uses a web scraping approach because Hetzner was not exposing a proper API before the REST one that is used by the new provider. Sadly, web scraping is way too brittle and push a maintainance burden, so we decided to drop it at the cost of a reduction of its scope. I hope this API will be extended to konsoleH.
