### ISSUE TITLE
autocmd should split by space

### ISSUE THREAD

**Issue by yonixw** [adferrand/dnsrobocert#112]
After renewal I wanted to reload nginx (like graceful reload in apache). Running `docker exec nginx nginx -s reload` works.

The problem:
[Autocmd code](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/hooks.py#L271) calls [execute code](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/utils.py#L22) with the entire command in one string while other args are seperated to a list.

This is a python\linux underlying issue, because it makes docker expect a file inside the docker named "nginx -s reload" (not only nginx)
* The python code `subprocess.call(['docker','exec','nginx','nginx -s reload'],env=env)`  **fails**
* while the following code **succeeds**: `subprocess.call(['docker','exec','nginx','nginx', '-s', 'reload'],env=env)` (last argument converted to list)

My current work around is to use the `deploy_hook: docker exec nginx nginx -s reload`. My suggested fix it to split the command and concatenate: `["docker", "exec", container, command]` will become `["docker", "exec", container] + command.split(' ')` in here : https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/hooks.py#L282

Anyway thanks for the project, use it a lot!

**Comment by davidyuk** [comment]
Another approach would be to allow define `cmd` in `autocmd` as a list

**Comment by yonixw** [comment]
> Another approach would be to allow define `cmd` in `autocmd` as a list

I think it will be a solution better then split since my solution will break the following example split by space: `echo "This should stay grouped"`

**Comment by adferrand** [comment]
Hello! Indeed the current approach is not correct, because one can not use a command with parameters, but a straight split by spaces would not work either if one of the parameters contains a space. I think there are several approaches to solve the issue:
1. Keep the command as a string
a. always interpret the string command in a shell, by using something like `subprocess.call("docker exec {0} {1}".format(container, command_str), shell=true)`
b. always interpret the string command outside of a shell, by continuing calling `subprocess.call(["docker", "exec", container, command_array])`, but converting first the string command into an array using `shlex.split()`, that takes into account shell subtilities like spaces in string parameters

2. Use an array command
a. always interpret the array command in a shell, by using `subprocess.call("docker exec {0} {1}".format(container, command_str), shell=true)`, while converting the array command into a string with `shlex.join`
b. always interpret the array command outside of a shell, with `subprocess.call(["docker", "exec", container, command_array])`

3) Accept both string command or array command
* if it is an array, use `subprocess.call(["docker", "exec", container, command_array])`
* if it is a shell, use `subprocess.call("docker exec {0} {1}".format(container, command_str), shell=true)`

I prefer option 3, because it does not rely on `shlex`, and because it is closely tied to how things are working in Dockerfiles, since both can be used, and related to the same interpretation (string in shell, array outside a shell).

What do you think of this?

**Comment by yonixw** [comment]
I agree 3 looks the right choice mainly because `it is closely tied to how things are working in Dockerfiles` as you said and thus will be what everyone expect when interacting with docker.

**Comment by davidyuk** [comment]
The third option is fine. It is better than the second because it doesn't make breaking changes 😉
