### ISSUE TITLE
DNS provider per domain

### ISSUE THREAD

**Issue by vaab** [adferrand/dnsrobocert#24]
All domains you may want to manage with this letsencrypt container might not use the same DNS provider... this doesn't seem to be managed by this image. Even if it doesn't seem very far from being possible.

The general idea would be to be able to provide a few configuration values for lexicon (let's say GANDI and OVH, and this is already possible thanks to your namespaced naming scheme for the environment variables), and thanks to a whois query on the domain, select the right provider for the domain.

How does that sound ?

**Comment by vaab** [comment]
Thrilled by your answer ! both your points, inclusion in lexicon and the possibility to provide a manual provider per domain name in this container are definitively the way to go.

On the lexicon side, of course this would perfectly go in the addon architecture, another entrypoint should be able to detect if a given domain is managed by the provider's plugin. I hope that in most case, with only a whois query, we can figure out who is the DNS provider... but I'm not 100% sure this will suffice in all cases (checking the registrar is only half of the problem, do all registrar have a IANA ID ? ... etc... ). I'm not very well versed in DNS infrastructure policies.

**Comment by vaab** [comment]
So shall we leave this open for tracking the ``docker-letsencrypt-dns`` container's task about implementing the possibility of assigning a provider per domain line ?

**Comment by adferrand** [comment]
Yes, we let this issue opened, but only for the automated resolution of the DNS provider from the nslookup. For the granularity of DNS provider configuration on each certificate, I opened #27 to discuss about the new major version of my container, which includes this functionality.

**Comment by adferrand** [comment]
@Analogj, I ping you about this discussion, that occurred for my Docker, but is in fact relevant for Lexicon.

To sum up, the idea would be to have an `auto` provider, that dynamically resolves the actual DNS provider using whois requests on the given domain. One problem was about handling correctly the same parameter (like `--auth-key`) for several provider, but we are going to resolve it with Analogj/lexicon#274.

So what do you think about that?

**Comment by AnalogJ** [comment]
oh I like that. We'd have to ensure that the WHOIS lookup-provider matching is accurate & up-to-date but yeah great idea. 

I'm usually on the side of explict configuration vs implict configuration but in this case I think its fine: its incredibly useful with guaranteed source of truth.

**Comment by adferrand** [comment]
@vaab @Analogj

About the IANA ID. The problem is that it is not the registar that we need to resolve, but the declared NS entries. Because one can register a domain with one registar, then delegate the DNS zone administration to any other provider, even your own bind9 instance. And it is this provider API that we need to target to make the modifications.

So we need to resolve every nameserver for every provider supported by Lexicon. They can be 1 or way more. We can have anycast server, or several versions of a provider, like for Gandi. And it needs to be maintained. Nothing impossible, but a significant complexity.

In parallel, there is always the possibility to create a manual mapping for each domain to a given provider. Either because a provider cannot be automatically be resolved, or because we want to gather in one place every mapping (like for my V3 specification). So something like `--domain-mapping` for the `auto` provider (+ env variable, config file, fallback as discussed).

**Comment by pascalandy** [comment]
This happens all the time:

> Because one can register a domain with one registar, then delegate the DNS zone administration to any other provider, even your own bind9 instance.

So let's say my client mnaage it's domain via it's own bluehost account. I ask him to point the CNAME to `mycorposerver.com/client123`.

Meanwhile, I generate my certificate using a DNS challenges on Cloudflare. Will this work? Reading this thread, I feel it will not.

Thank you again!

**Comment by adferrand** [comment]
Between the `auto` provider, and capacity of DNSroboCert to use different providers and even several configurations for the same provider, I believe this issue can be closed. Feel free to comment!
