### ISSUE TITLE
renew notification

### ISSUE THREAD

**Issue by Azertooth** [adferrand/dnsrobocert#592]
First, thank you for this amazing piece of code, it's amazing and it works perfectly!
I wanna ask you how could I trigger some kind of notification (I would prefere telegram but email is fine too) at certification renewing, both if successful and not. I use the docker container version and I could work on a stdout based shell script too; do you have any suggestion?

**Comment by adferrand** [comment]
Hello @Azertooth, thanks a lot!

To execute an arbitrary logic upon certificate creation or renewal, you can use the `deploy_hook` parameter in a `certificate` section (https://dnsrobocert.readthedocs.io/en/latest/configuration_reference.html#certificates-section). Basically it defines a shell command that will be executed when a certificate is created or renewed.

Given this parameter, you can mount the script you need inside the docker container so that it is executed at the right time. I would recommend to use the tools already available in the image to avoid to build and maintain your own image. You have curl, and obviously python, which are quite sufficient to send some calls (like HTTP requests) to an external system that will execute the actual logic you want.

**Comment by Azertooth** [comment]
> Hello @Azertooth, thanks a lot!
> 
> To execute an arbitrary logic upon certificate creation or renewal, you can use the `deploy_hook` parameter in a `certificate` section (https://dnsrobocert.readthedocs.io/en/latest/configuration_reference.html#certificates-section). Basically it defines a shell command that will be executed when a certificate is created or renewed.
> 
> Given this parameter, you can mount the script you need inside the docker container so that it is executed at the right time. I would recommend to use the tools already available in the image to avoid to build and maintain your own image. You have curl, and obviously python, which are quite sufficient to send some calls (like HTTP requests) to an external system that will execute the actual logic you want.

f-a-n-t-a-s-t-i-c !
that's exactly what I was looking for, a simple, integrated solution to keep all tidy and KISS! I will build my notification on that parameter I was totally ignoring, thanks again for the heads up!
