### ISSUE TITLE
TransIP provider requires additional dependencies.

### ISSUE THREAD

**Issue by silvanverschuur** [adferrand/dnsrobocert#617]
I'm trying to migrate from a custom script + certbot to this Docker container. I want to use the TransIP provider to update my DNS records. If I try to start the container I get the following error message:

```
This provider (transip) has required dependencies that are missing. Please install lexicon[transip] first.
```

According to the Lexicon documentation this can be done by

```
python3 -m pip install dns-lexicon[transip]
```

Do I have to do this manually or should this container already contain all necessary dependencies? As a workaround I have overridden the entrypoint with a custom script that installs the transip pakages and executes `/run/sh` afterwards. I'm not sure if this is the right way to do this.

**Comment by adferrand** [comment]
Hello @silvanverschuur ! I think your problem is related to what is described in https://github.com/adferrand/dnsrobocert/issues/549.

Basically I had been forced to remove the transip dependency for now because of several incompatibilities. I am working to get it work again with the new REST API proposed by TransIP. As a temporary workaround, you can stick with DNSRoboCert 3.12.0.

I close this issue but do not hesitate to use the other one for future discussions.
