### ISSUE TITLE
--force-renewal?

### ISSUE THREAD

**Issue by sirudog** [adferrand/dnsrobocert#68]
Hi, amazing project!
One question, did not find any info about how to force cert renewal (the `--force-renewal` param of certbot). Could be handy in staging mode for testing. Can this be done?

**Comment by sirudog** [comment]
Ok, maybe one way to do it is by exec into the container and run certbot directly with `--force-renewal`

**Comment by sirudog** [comment]
So to confirm, I could do it like this:
1. docker exec -it [container] sh
2. based on this: https://github.com/adferrand/docker-letsencrypt-dns/blob/master/files/watch-domains.sh#L58-L70run a tailor-made command

**Comment by adferrand** [comment]
Hello @sirudog! In fact, the way your are doing it is precisely how I do it to develop the Docker image. Arguably we could make it a little more easy to pass arbitrary flags to certbot if needed. I think I will add a `CERTBOT_OPTIONS` env variable for that, similarly to `LEXICON_OPTIONS` for lexicon.

What do you think of that?

**Comment by Codelica** [comment]
I'd welcome some option for forced renewal.  Let's Encrypt just sent out notices about a bug in some their code that requires them to revoke a bunch of certs quickly (i.e. tomorrow :( )  So I need to force renew several across several servers.

I wasn't able to to run a command like above until I added:

```
                --agree-tos \
                --email myemail@something.com \
```

ENV vars would be fine, but some option in domains.conf that could get picked up on container restart would be even easier IMO. (vs container re-creations to add and remove ENV vars)

Thanks for this project!

**Comment by adferrand** [comment]
> I'd welcome some option for forced renewal. Let's Encrypt just sent out notices about a bug in some their code that requires them to revoke a bunch of certs quickly (i.e. tomorrow :( ) So I need to force renew several across several servers.
> 
> I wasn't able to to run a command like above until I added:
> 
> ```
>                 --agree-tos \
>                 --email myemail@something.com \
> ```
> 
> ENV vars would be fine, but some option in domains.conf that could get picked up on container restart would be even easier IMO. (vs container re-creations to add and remove ENV vars)
> 
> Thanks for this project!

Indeed, I just validated the PR on certbot that gives to it the ability to renew immediately certificates that are claimed to be expired through OCSP call. New version of Certbot is released today, and I will release my Docker immediately after.

This will allow all certificates impacted by the bug to be renewed.

I am a little concerned by providing a environment variable that would force renew globally. Indeed, considering the typical use case here, this would trigger a lot of certificate per accounts to be renewed at once. Then most likely the target account would be block to renew for the next 24 hours because rate limit has been reached on Let'sEncrypt servers, and this would be counterproductive.

**Comment by lusu007** [comment]
Hey @adferrand ,
first of all many thanks for this fantastic image. I'm using it on multiple projects!

Is there an ETA when you release the new version? I'm a bit concerned that my services could suffer from security warnings...

Many thanks,
Lukas

**Comment by adferrand** [comment]
Version 2.23.0 is release. It ships with certbot 1.3.0, that renews early certificates when they have been revoked.

**Comment by lusu007** [comment]
So I dont have to force renew when certbot renews automatically?

**Comment by adferrand** [comment]
Indeed, you do not have to force renew. It will renew the impacted certificates (and only them) because their OCSP status indicate that they have been revoked by Let's Encrypt.

**Comment by adferrand** [comment]
Hello!

Now that I migrated the project in a complete new stack, you can now specifically force renew a certificate, by providing `force_renew: true` in the relevant certificate configuration. See https://dnsrobocert.readthedocs.io/en/latest/configuration_reference.html#certificate-properties for more details.

Note that the force renew is not applied to the automated renew, that is run twice a day. It is triggered only when the configuration file is changed, or when you restart `dnsrobocert`, in order to avoid wild and silent force renews.
